services:

  url-service:
    build: ./url-service

    ports:
      - "5000:5000"

    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: taskuser
      DB_PASSWORD: taskpassword
      DB_NAME: taskdb

    networks:
      - microservices-network

    depends_on:
      db:
        condition: service_healthy
      analytics-service:
        condition: service_started
      redis:
        condition: service_healthy

  analytics-service:
    build: ./analytics-service

    networks:
      - microservices-network
    
    depends_on:
      redis:
        condition: service_healthy


  db:
    image: postgres:17-alpine

    environment:
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpassword
      POSTGRES_DB: taskdb

    volumes:
      - db-data:/var/lib/postgresql/data

    networks:
      - microservices-network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskuser -d taskdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data

    networks:
      - microservices-network

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      
volumes:
  db-data:
  redis-data:

networks:
  microservices-network: