apiVersion: apps/v1

kind: Deployment

metadata:
  name: analytics-service
  namespace: url-shortener

spec:
  replicas: 1

  selector:
    matchLabels:
      app: analytics-service

  template:
    metadata:
      labels:
        app: analytics-service

    spec:
      containers:
        - name: analytics-service
          image: docker-microservices-analytics-service:latest
          imagePullPolicy: IfNotPresent

          resources:
              requests:
                cpu: "50m"
                memory: "64Mi"
              limits:
                cpu: "250m"
                memory: "128Mi"

          readinessProbe:
            httpGet:
              path: /
              port: 6001
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 6001
            initialDelaySeconds: 5
            periodSeconds:  10
            
            

          ports:
            - containerPort: 6001
            
          env:
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: analytics-service-config
                  key: REDIS_URL
