apiVersion: v1
kind: Secret

metadata:
  name: postgres-secret
  namespace: url-shortener
  
type: Opaque

stringData:
  POSTGRES_USER: taskuser
  POSTGRES_PASSWORD: taskpassword
  POSTGRES_DB: taskdb