apiVersion: apps/v1

kind: Deployment

metadata:
  name: url-service
  namespace: url-shortener
  
spec:
  replicas: 3

  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: url-service

  template:
    metadata:
      labels:
        app: url-service
  

    spec:
      serviceAccountName: url-service

      containers:
        - name: url-service
          image: url-service:v2
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 5000

          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 100

          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds:  10

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
              

          env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: url-service-config
                key: DB_HOST

          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: url-service-config
                key: DB_PORT

          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_USER

          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD

          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_DB
