apiVersion: apps/v1

kind: Deployment

metadata:
  name: url-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: url-service

  template:
    metadata:
      labels:
        app: url-service

    spec:
      containers:
        - name: url-service
          image: docker-microservices-url-service:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 5000

          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 100

          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds:  10

          env:
          - name: DB_HOST
            value: "postgres"

          - name: DB_PORT
            value: "5432"

          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_USER

          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD

          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_DB
